unit PASSWORD;

interface

uses Winapi.Windows, System.SysUtils, System.Classes, Vcl.Graphics, Vcl.Forms,
  Vcl.Controls, Vcl.StdCtrls, Vcl.Buttons, Vcl.ExtCtrls, Dialogs, Vcl.Themes,
  Vcl.CustomizeDlg;

type
  TCreatFastLog = class(TForm)
    Label1: TLabel;
    pass: TEdit;
    OKBtn: TButton;
    CancelBtn: TButton;
    login: TEdit;
    depart: TEdit;
    Label2: TLabel;
    Label3: TLabel;
    Panel1: TPanel;
    vi: TEdit;
    Label4: TLabel;
    serv_url: TEdit;
    Label5: TLabel;
    Memo1: TMemo;
    RG: TRadioGroup;
    Bevel1: TBevel;
    CustomizeDlg1: TCustomizeDlg;
    cbRegistredStyles: TComboBox;
    procedure OKBtnClick(Sender: TObject);
    procedure CancelBtnClick(Sender: TObject);
    procedure loginAs(Sender: TObject);
    procedure AddStyles(Sender: TObject);
    procedure ChStyle(Sender: TObject);

  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  CreatFastLog: TCreatFastLog;

implementation

{$R *.dfm}

procedure TCreatFastLog.AddStyles(Sender: TObject);
var  i: integer;
begin
  for i := 0 to Length(TStyleManager.StyleNames)-1 do cbRegistredStyles.Items.Add(TStyleManager.StyleNames[i]);
  cbRegistredStyles.ItemIndex:=0;
end;

procedure TCreatFastLog.CancelBtnClick(Sender: TObject);
begin
Application.Terminate;
end;

procedure TCreatFastLog.ChStyle(Sender: TObject);
begin
  TStyleManager.TrySetStyle(cbRegistredStyles.Items[cbRegistredStyles.ItemIndex], false);
end;

procedure TCreatFastLog.OKBtnClick(Sender: TObject);
var
rd: string;
rStr: string;
begin
if (RG.ItemIndex=0) then begin
  if ((depart.Text<>'') and (login.Text<>'') and (pass.Text<>'')) then begin
    if (vi.Text='') then vi.Text:='10';
//   CreatFastLog.Height:=317;
    rd:=serv_url.Text+'sh_tab_xls_v'+vi.Text+'.php';
    rStr:='location.href="'+rd+'?rnd=1&us='+depart.Text+'___0_'+login.Text+'___0_'+pass.Text+'";';
    Memo1.Lines.Clear;
    Memo1.Lines[0]:='<HTML><HEAD>';
    Memo1.Lines.Add('<TITLE>FAST LOGIN PAGE</TITLE>');
    Memo1.Lines.Add('</HEAD><BODY>');
    Memo1.Lines.Add('<!-- Generated by FastLog Creator -->');
    Memo1.Lines.Add('<h3>Fast login</h3>');
    Memo1.Lines.Add('<SCRIPT>');
    Memo1.Lines.Add(rStr);
    Memo1.Lines.Add('</SCRIPT>');
    Memo1.Lines.Add('</BODY></HTML>');
    Memo1.Lines.SaveToFile('fastlogin.htm');
    ShowMessage('Успешно завершено!');
  end
  else ShowMessage('Сперва заполните все поля!');
end;
if (RG.ItemIndex=1) then begin
    if (vi.Text='') then vi.Text:='10';
    rd:='r=Math.random();';
    rStr:='location.href="'+serv_url.Text+'adm3.php?s=1&us=0___0_0___0_0&r="+r;';
    Memo1.Lines.Clear;
    Memo1.Lines[0]:='<HTML><HEAD>';
    Memo1.Lines.Add('<TITLE>FAST LOGIN ADM PAGE</TITLE>');
    Memo1.Lines.Add('</HEAD><BODY>');
    Memo1.Lines.Add('<!-- Generated by FastLog Creator -->');
    Memo1.Lines.Add('<h3>Fast login</h3>');
    Memo1.Lines.Add('<SCRIPT>');
    Memo1.Lines.Add(rd);
    Memo1.Lines.Add(rStr);
    Memo1.Lines.Add('</SCRIPT>');
    Memo1.Lines.Add('</BODY></HTML>');
    Memo1.Lines.SaveToFile('admlogin.htm');
    ShowMessage('Успешно завершено!');
end;

end;



procedure TCreatFastLog.loginAs(Sender: TObject);
begin
  if (RG.ItemIndex=0) then begin
    depart.Enabled:=true;
    login.Enabled:=true;
    pass.Enabled:=true;
    label2.Enabled:=true;
    label3.Enabled:=true;
    label1.Enabled:=true;
  end
  else begin
    depart.Enabled:=false;
    login.Enabled:=false;
    pass.Enabled:=false;
    label2.Enabled:=false;
    label3.Enabled:=false;
    label1.Enabled:=false;
  end;
end;

end.

