// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Project1;

{ITE} {DFMFileType} {PassWord.dfm}
{ITE} {RCFileType} {Win32\Release\Project1_DRC.rc}

{$R 'PassWord.dfm' 'CreatFastLog:TForm'}
{$R 'Win32\Release\Project1_DRC.res' 'Win32\Release\Project1_DRC.rc'}

{$E ENU}

begin
end.
